config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  post 'cards/:id/add_people', to: 'cards#add_people'
  get 'cards/:id/add_people', to: 'cards#add_people'
  get 'ideas', to: 'cards#ideas'
  get 'actions', to: 'cards#actions'
  resources :cards do
    resources :participants
  end
  get 'categories/list', to: 'categories#list'
  resources :categories do
    resources :cards
  end
  resources :materials
  resources :users do
    get 'owned_cards', to: 'users#owned_cards'
    get 'joined_cards', to: 'users#joined_cards'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Ignore created_at and updated_at by default in JSONs
  # and when needed add them to :include
  def serializable_hash(options={})
    options[:except] ||= []
    options[:except] << :created_at unless (options[:include] == :created_at) || (options[:include].kind_of?(Array) && (options[:include].include? :created_at))
    options[:except] << :updated_at unless (options[:include] == :updated_at) || (options[:include].kind_of?(Array) && (options[:include].include? :updated_at))

    options.delete(:include) if options[:include] == :created_at
    options.delete(:include) if options[:include] == :updated_at
    options[:include] -= [:created_at, :updated_at] if options[:include].kind_of?(Array)

    super(options)
  end
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :owner, foreign_key: "owner_id", class_name: "User", optional: true
  has_many :participants, foreign_key: "card_id", class_name: "Participant"
  has_many :materials

  before_validation :sanitize_content, :on => :create

  def sanitize_content
    self.description = ActionController::Base.helpers.sanitize(self.description)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cards
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :card
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :card
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :owned_cards, foreign_key: "owner_id", class_name: "Card"
  has_many :joined_cards, foreign_key: "user_id", class_name: "Participant"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    if params[:category_id]
      @cards = Card.where(category_id:params[:category_id])
    else
      @cards = Card.all
    end
    render status: 200
  end

  def ideas
    @cards = Card.where(is_action:false)
    render status: 200
  end

  def actions
    @cards = Card.where(is_action:true)
    render status: 200
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.people_interested = 0
    @card.category = Category.find_by(name:"Outros") if !@card.category
    @card.save
    material = Material.new(
      name: params[:material_name],
      quantity_needed: params[:material_quantity],
      card_id: @card.id
    )
    @card.materials << material unless material.save
    render "show"
  end

  def show
    @card = Card.find(params[:id])
  end

  def add_people
    @card = Card.find(params[:id])
    @card.people_interested += 1
    @card.save
    @card.update_attributes(is_action:true) unless @card.people_interested < @card.people_needed
    render status: 200, json: @card.to_json
  end

  private

  def card_params
    params.permit(
      :title,
      :description,
      :people_interested,
      :category_id,
      :people_needed,
      :time,
      :location,
      :owner_id,
      materials_attributes: [:name, :quantity, :id]
    )
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @categories = Category.all
    render status: 200, json: @categories.to_json
  end

  def list
    @categories = Category.all.map {|category| {name: category.name, id:category.id} }
    render status: 200, json: @categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    render status: 200, json: @category.to_json
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    render status: 200, json: @category.to_json
  end

  def show
    @category = Category.find(params[:id])
    render status: 200, json: @category.to_json
  end

  private

  def category_params
    params.permit(:name,:image_url)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @materials = Material.all
    render status: 200, json: @materials.to_json
  end

  def list
    @materials = Material.all.map {|material| {name: material.name, id:material.id} }
    render status: 200, json: @materials
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.create(material_params)
    render status: 200, json: @material.to_json
  end

  def show
    @material = Material.find(params[:id])
    render status: 200, json: @materials.to_json
  end

  private

  def material_params
    params.permit(
      :name,
      :quantity,
      :card_id
    )
  end
  
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
    @participants = Participant.where(card_id:params[:card_id])
    render status: 200, json: @participants.to_json
  end
  def new
    @participant = Participant.new(card_id:params[:card_id])
  end
  def create
    @participant = Participant.create(participant_params)
    render status: 200, json: @participant.to_json
  end
  private
  def participant_params
    params.permit(:card_id,:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    render status: 200, json: @user.to_json
  end

  def owned_cards
    @cards = Card.where(owner_id:params[:user_id])
  end

  def joined_cards
    @cards = Card.joins(:participants).where(participants:{ user_id: params[:user_id] })
  end

  private
  def user_params
    params.permit(:name,:email,:password,:phone)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @text_field = <<-HEREDOC

    Receber o index dos cards idéias
    GET    /ideas

    Receber o index dos cards ações
    GET    /actions

    Criar um novo card
    POST   /cards
    parametros
      title,
      description,
      people_interested,
      category_id,
      people_needed,
      time,
      location,
      owner_id

    Receber informações de um card específico
    GET    /cards/:id

    Adicionar +1 a quantidade de pessoas interessadas no card
    POST   /cards/:id/add_people

    Criar uma nova categoria
    POST   /categories
    parametros:
      name

    Receber um array com todas categorias (como nome e id para o select, a form de criar um card envia só o ID da categoria)
    GET    /categories/list

    Criar um usuário (Vai retornar o usuário criado com ID dele, se tiver como guarda esse ID dele)
    POST   /users
    parametros:
      name,
      email,
      password

    Receber os participantes de um card
    GET    /cards/:card_id/participants

    Adicionar um participante a um card (precisa do ID de um usuário que foi criado)
    POST   /cards/:card_id/participants
    parametros:
      user_id

    Receber todos os cards de uma categoria específica
    GET   /categories/:category_id/cards

    Receber todos card criados por um usuário específico
    GET   /users/:user_id/owned_cards

    Receber todos card que um usuário específico vai participar
    GET   /users/:user_id/joined_cards

    HEREDOC
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_old_index.html.erb
CARDS! \o/
<hr>

<div>
<% @cards.each do |card| %>
  id: <%= card.id %><br>
  title: <%= card.title %><br>
  description<%= card.description %><br>
  <br>
<% end %>
</div>


<br> <%= link_to "criar card", new_card_path %>

app/views/cards/index.html.erb
CARDS! \o/
<hr>

<div>
<% @cards.each do |card| %>
  id: <%= card.id %><br>
  title: <%= card.title %><br>
  description<%= card.description %><br>
  <br>
<% end %>
</div>


<br> <%= link_to "criar card", new_card_path %>

app/views/cards/new.html.erb
<%= form_tag("/cards", method: "post") do %>
  <%= label_tag(:title, "title") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:description, "description") %>
  <%= text_field_tag(:description) %>
  <%= label_tag(:people_needed, "people_needed") %>
  <%= text_field_tag(:people_needed) %>
  <%= label_tag(:category_id, "category_id") %>
  <%= select_tag(:category_id,options_for_select(Category.all.map {|category| [category.name, category.id]})) %>
  <%= label_tag(:location, "location") %>
  <%= text_field_tag(:location) %>
  <%= label_tag(:time, "time") %>
  <%= date_field_tag(:time) %>
  <%= label_tag(:material_name, "material_name") %>
  <%= text_field_tag(:material_name) %>
  <%= label_tag(:material_quantity, "material_quantity") %>
  <%= text_field_tag(:material_quantity) %>
  <br>
  <%= submit_tag("create") %>
<% end %>

app/views/categories/edit.html.erb
<%= form_tag("/categories/#{@category.id}", method: "patch") do %>
  <%= label_tag(:name, "name") %>
  <%= text_field_tag(:name, @category.name) %>
  <%= label_tag(:image_url, "image_url") %>
  <%= text_field_tag(:image_url,  @category.image_url) %>
  <br>
  <%= submit_tag("update") %>
<% end %>

app/views/categories/new.html.erb
<%= form_tag("/categories", method: "post") do %>
  <%= label_tag(:name, "name") %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:image_url, "image_url") %>
  <%= text_field_tag(:image_url) %>
  <br>
  <%= submit_tag("create") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Integra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/materials/new.html.erb
<%= form_tag("/materials", method: "post") do %>
  <%= label_tag(:name, "name") %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:quantity, "quantity") %>
  <%= number_field_tag(:quantity) %>
  <%= label_tag(:card_id, "card_id") %>
  <%= number_field_tag(:card_id) %>
  <br>
  <%= submit_tag("create") %>
<% end %>

app/views/participants/new.html.erb
<%= form_tag("/cards/#{@participant.card_id}/participants", method: "post") do %>
  <%= label_tag(:user_id, "user_id") %>
  <%= text_field_tag(:user_id) %>
  <br>
  <%= submit_tag("create") %>
<% end %>

app/views/users/new.html.erb
<%= form_tag("/users", method: "post") do %>
  <%= label_tag(:name, "name") %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:email, "email") %>
  <%= text_field_tag(:email) %>
  <%= label_tag(:password, "password") %>
  <%= text_field_tag(:password) %>
  <br>
  <%= submit_tag("create") %>
<% end %>

app/views/welcome/index.html.erb
<h1>WELCOME WORLD TO THE WONDERFUL INTEGRA APP</h1>

<%= simple_format(@text_field) %>